language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

before_deploy: echo "eriksanne.com" > ./dist/CNAME

deploy:
  edge: true
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: dist
  repo: ersanne/ersanne.github.io
  target_branch: master
  on:
    branch: master
